package com.frcodes.administration.model;

import java.util.Date;

import javax.annotation.PostConstruct;

public class User {

	// Autogenerated
	private String userId;

	private String name;

	private String surname;

	private Date date;

	private Boolean enabled;

	public User() {
		this.init();
	}

	public void init() {
		userId = (String.valueOf((new Date()).getTime()));
		date = new Date();
		enabled = Boolean.TRUE;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Boolean getEnabled() {
		return enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

}
